export const tokens = {
  colors: {
    primary: 'var(--navi-color-primary)',
    primaryLight: 'var(--navi-color-primary-light)',
    primaryDark: 'var(--navi-color-primary-dark)',
    neutral: 'var(--navi-color-neutral)',
    neutralLight: 'var(--navi-color-neutral-light)',
    neutralDark: 'var(--navi-color-neutral-dark)',
    success: 'var(--navi-color-success)',
    warning: 'var(--navi-color-warning)',
    destructive: 'var(--navi-color-destructive)',
    info: 'var(--navi-color-info)',
    surface: 'var(--navi-color-surface)',
    surfaceHover: 'var(--navi-color-surface-hover)',
    surfaceActive: 'var(--navi-color-surface-active)',
    overlay: 'var(--navi-color-overlay)',
    overlayLight: 'var(--navi-color-overlay-light)',
    ink: 'var(--navi-color-ink)',
    border: 'var(--navi-color-border)',
    borderDark: 'var(--navi-color-border-dark)',
    inverse: 'var(--navi-color-inverse)',
  },
  radius: {
    sm: 'var(--navi-radius-sm)',
    md: 'var(--navi-radius-md)',
    lg: 'var(--navi-radius-lg)',
  },
  shadow: {
    sm: 'var(--navi-shadow-sm)',
    md: 'var(--navi-shadow-md)',
    lg: 'var(--navi-shadow-lg)',
    xl: 'var(--navi-shadow-xl)',
  },
} as const